# https://taskfile.dev

version: '3'

vars:
  APP:
    sh: basename $PWD
  DIST: dist
  GO_PACKAGES:
    sh: go list ./...

tasks:
  default:
    cmds:
      - task: test

  dist:
    cmds:
      - mkdir -p {{.DIST}}

  lint:
    desc: Runs golint
    cmds:
      - golangci-lint -v run

  test:
    desc: Run tests
    deps: [dist]
    cmds:
      - go test {{.CLI_ARGS}} -race -count=1 -covermode atomic -coverprofile {{.DIST}}/coverage.txt ./...

  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST}}

  snapshot:
    desc: Build a snapshot
    deps: [test, lint]
    cmds:
      - goreleaser --debug release --snapshot --rm-dist
